name: Docker Image CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - master
    - modules

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      DOCKER_IMAGE: ${{ github.repository }}:${{ github.sha }}

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Docker build
      run: docker build . --file Dockerfile --tag ${DOCKER_IMAGE}

    - name: Print Hugo version
      run: docker run --rm ${DOCKER_IMAGE} version


  hadolint:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: hadolint
      run: |
        brew install hadolint
        hadolint ./Dockerfile
