name: Docker Image CI

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
    - '**.md'
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      DOCKER_IMAGE: ${{ github.repository }}:${{ github.sha }}

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Set env
      run: |
        echo "::set-env name=LATEST::${DOCKER_IMAGE}:latest"
        echo "::set-env name=LATEST_MOD::${DOCKER_IMAGE}:latest-mod"

    - name: Build alpine image
      run: |
        docker build . -t "${LATEST}"

    - name: Build golang image
      run: |
        docker build . -t "${LATEST_MOD}" --build-arg BASE_IMAGE=golang:1.13-alpine3.10"

    - name: Print Hugo version
      run: |
        docker run --rm ${LATEST} version
        docker run --rm ${LATEST_MOD} version


  hadolint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: brew install hadolint
    - run: hadolint ./Dockerfile
