name: Push to Package Registry

on:
  release:
    types: [published]

env:
  DOCKER_BASE_NAME: docker.pkg.github.com/${{ github.repository }}/hugo
  DOCKER_HUB_BASE_NAME: peaceiris/hugo
  TAG_NAME: ${{ github.event.release.tag_name }}

jobs:

  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "${GITHUB_CONTEXT}"

    - name: Set env
      run: |
        echo "::set-env name=PKG_TAG::${DOCKER_BASE_NAME}:${TAG_NAME}"
        echo "::set-env name=PKG_TAG_MOD::${DOCKER_BASE_NAME}-mod:${TAG_NAME}"
        echo "::set-env name=HUB_TAG::${DOCKER_HUB_BASE_NAME}:${TAG_NAME}"
        echo "::set-env name=HUB_TAG_MOD::${DOCKER_HUB_BASE_NAME}:${TAG_NAME}-mod"

    - name: Build alpine image
      run: |
        docker build . -t "${PKG_TAG}"
        docker tag "${PKG_TAG}" "${HUB_TAG}"

    - name: Build golang image
      run: |
        docker build . -t "${PKG_TAG_MOD}" --build-arg BASE_IMAGE=golang:1.13-alpine3.10
        docker tag "${PKG_TAG_MOD}" "${HUB_TAG_MOD}"

    - name: Login to Registries
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: |
        echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u peaceiris --password-stdin
        echo "${DOCKER_HUB_TOKEN}" | docker login -u peaceiris --password-stdin

    - name: Push tag
      run: |
        docker push "${PKG_TAG}"
        docker push "${PKG_TAG_MOD}"
        docker push "${HUB_TAG}"
        docker push "${HUB_TAG_MOD}"
